version: '3.6'
services:
  server:
    build: .
    command:
      - nix-shell
      - --run
      - 'cd plutus-playground-client && plutus-playground-server'
    ports:
      - '8080:8080'
  client:
    build: .
    command:
      - nix-shell
      - --run
      - 'cd plutus-playground-client && npm run start'
    depends_on:
      - server
    ports:
      - '8009:8009'
    links:
      - server
